name: Ubuntu
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
