name: Ubuntu
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
